services:
  - type: web
    name: weather-app-backend
    env: docker
    rootDir: Backend
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: weather-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: weather-app-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: weather-app-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: weather-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: weather-app-db
          property: password

databases:
  - name: weather-app-db
    databaseName: weather_app
    user: weather_user
    plan: free